# Generated by Django 2.2.1 on 2019-05-30 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('title', models.CharField(db_index=True, max_length=80)),
                ('description', models.SlugField(max_length=200)),
                ('rooms_count', models.IntegerField(db_index=True)),
                ('price_USD', models.FloatField(db_index=True)),
                ('price_UAH', models.FloatField(db_index=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('district', models.CharField(db_index=True, max_length=80)),
                ('sku', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('image_url', models.CharField(db_index=True, default='Not found image', max_length=80)),
                ('published_at', models.DateField(default=datetime.datetime(2019, 5, 30, 20, 21, 27, 430912, tzinfo=utc))),
            ],
        ),
    ]
