# Generated by Django 2.2.1 on 2019-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=80)),
                ('description', models.SlugField(max_length=200)),
                ('price_USD', models.FloatField(db_index=True)),
                ('price_UAH', models.FloatField(db_index=True)),
                ('district', models.CharField(db_index=True, max_length=80)),
                ('rooms_count', models.IntegerField(db_index=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
