# Generated by Django 2.2.1 on 2019-05-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='date_pub',
        ),
    ]
