# Generated by Django 2.2.1 on 2019-05-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20190530_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='published_at',
            field=models.DateField(),
        ),
    ]
