# Generated by Django 2.2.1 on 2019-05-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20190530_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='published_at',
        ),
    ]
